#include<stdio.h>

int main(int argc,char *argv[]) {
  int token;
  while (token = yylex()) {
    switch (token) {
      case MULTI_COMMENT: printf("<MULTI LINE COMMENT, %d>\n", token);
        break;
      case SINGLE_COMMENT:  printf("<SINGLE LINE COMMENT, %d>\n", token);
        break;
      case AUTO:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case BREAK: printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case CASE:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case CHAR:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case CONST: printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case CONTINUE:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case DEFAULT: printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case DO:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case DOUBLE:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case ELSE:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case ENUM:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case EXTERN:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case FLOAT: printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case FOR: printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case GOTO:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case IF:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case INLINE:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case INT: printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case LONG:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case REGISTER:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case RESTRICT:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case RETURN:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case SHORT: printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case SIGNED:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case SIZEOF:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case STATIC:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case STRUCT:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case SWITCH:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case TYPEDEF: printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case UNION: printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case UNSIGNED:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case VOID:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case VOLATILE:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case WHILE: printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case _BOOL: printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case _COMPLEX:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case _IMAGINARY:  printf("<KEYWORD, %d, %s>\n", token, yytext);
        break;
      case ID:  printf("<IDENTIFIER, %d, %s>\n", token, yytext); 
        break;
      case INT_CONST:   printf("<INTEGER CONSTANT, %d, %s>\n", token, yytext); 
        break;
      case FLOAT_CONST:   printf("<FLOAT CONSTANT, %d, %s>\n", token, yytext); 
        break;
      case ENUM_CONST:  printf("<ENUMERATION CONSTANT, %d, %s>\n", token, yytext); 
        break;
      case CHAR_CONST:  printf("<CHAR CONSTANT, %d, %s>\n", token, yytext); 
        break;
      case STRING_CONST:  printf("<STRING CONSTANT, %d, %s>\n", token, yytext); 
        break;
      case LSQBRACKET:  printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case RSQBRACKET:  printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case LBRACE: printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case RBRACE: printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case LPARAN: printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case RPARAN: printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case DOT:   printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case ARROW:   printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case INCREMENT:   printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case DECREMENT:   printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case BIT_AND:   printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case BIT_OR:  printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case BIT_XOR:   printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case BIT_NOT:   printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case PLUS:  printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case SUB:   printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case MULT:  printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case DIV:   printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case MOD:   printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case LOG_NOT:   printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case LOG_AND:   printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case LOG_OR:  printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case RIGHTSHIFT:  printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case LEFTSHIFT:   printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case LESS:  printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case GREATER:   printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case LESSEQ:  printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case GREATEREQ:   printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case EQUALS:  printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case NOTEQ:   printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case QUES:  printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case COLON:   printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case SEMICOLON: printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case ELLIPSIS:  printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case ASSIGN: printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case PLUS_ASSGN:  printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case SUB_ASSGN:   printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case MULT_ASSGN:  printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case DIV_ASSGN:   printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case LEFT_SHIFT_ASSGN:  printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case RIGHT_SHIFT_ASSGN:   printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case AND_ASSGN:   printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case OR_ASSGN:  printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case XOR_ASSGN:   printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case COMMA:   printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      case HASH:  printf("<PUNCTUATOR, %d, %s>\n", token, yytext); 
        break;
      
    }
  }
  return 0;
}